\ run tests with: gforth Tests.fs

S" BankOcr.fs" REQUIRED

: AUTOTEST
    ASSERT( BL       BAR? 0 = )
    ASSERT( [CHAR] | BAR? 1 = )
    ASSERT( [CHAR] _ BAR? 1 = )

    ASSERT( 0 0 OCR-ADDRESS OCR-BUFFER 1  + = )
    ASSERT( 0 1 OCR-ADDRESS OCR-BUFFER 27 + = )
    ASSERT( 0 2 OCR-ADDRESS OCR-BUFFER 28 + = )
    ASSERT( 0 3 OCR-ADDRESS OCR-BUFFER 29 + = )
    ASSERT( 0 4 OCR-ADDRESS OCR-BUFFER 54 + = )
    ASSERT( 0 5 OCR-ADDRESS OCR-BUFFER 55 + = )
    ASSERT( 0 6 OCR-ADDRESS OCR-BUFFER 56 + = )
    ASSERT( 1 0 OCR-ADDRESS OCR-BUFFER 4  + = )
    ASSERT( 1 1 OCR-ADDRESS OCR-BUFFER 30 + = )
    ASSERT( 1 2 OCR-ADDRESS OCR-BUFFER 31 + = )
    ASSERT( 8 6 OCR-ADDRESS OCR-BUFFER 80 + = )
    

    ." TESTS PASSED"
    DEPTH ?DUP IF CR .S THEN 
;

AUTOTEST CR

BYE
